version: "3.0"
services:
  postgres:
    image: f
    container_name: ffserver-versatile-dev
    network_mode: "host"
    # restart: always
    volumes:
      - ./video_samples:/app/video_samples
      - ./workspace:/app/workspace
    environment:
      - LOG_LEVEL=DEBUG
      - INERNAL_PORTS=40000,30000,30001,30002
      - EXTERNAL_PORTS=41000,31000,31001,31002
      - NUM_COPIES=1
      - SHIFT_INTERVAL=0
      - FRAME_RATE=30
      - EACH_STREAM_MAX_BANDWIDTH=10000
      - SKIP_RESIZE=False
      - RESIZE_RESOLUTION=1920x1080
      - ALLOWED_EXTENTIONS=.mp4
      - WORKERS_NUM_LIMIT=32
